<?php

namespace Database\Seeders;

use App\Models\Referencia;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ReferenciaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $referencias = [
                        ['nombre' => 'COD 628 Pago de Regalías', 'seleccion' => '0'],
                        ['nombre' => 'COD 101 Expo - Orden de Pago', 'seleccion' => '0'],
                        ['nombre' => 'B14 Cancelación de garantías comerciales de Bancos por Impo de Bs con registro de ingreso aduanero', 'seleccion' => '0'],
                        ['nombre' => 'P13 Pagos de principal de deudas financieras con el exterior originadas en importaciones de bienes', 'seleccion' => '0'],
                        ['nombre' => 'INTERESES DE PREFINANCIACIÓN', 'seleccion' => '0'],
                        ['nombre' => 'COD 102 Expo-Cobros Anticipados', 'seleccion' => '0'], 
                        ['nombre' => 'COD 111 FINANCIACIÓN DE EXPO', 'seleccion' => '0'],
                        ['nombre' => 'COD 103 PreFi de exportaciones del exterior', 'seleccion' => '0'],
                        ['nombre' => 'Remanente - Exportación (101)', 'seleccion' => '0'],
                        ['nombre' => 'Cancelación Finan de Impo', 'seleccion' => '0'],
                        ['nombre' => 'COD 745 Utilidades y dividendos pagados al exterior', 'seleccion' => '0'],
                        ['nombre' => 'COD 156 IMPO- PAGO ANTICIPADO', 'seleccion' => '0'],
                        ['nombre' => 'COD 153 - 157 IMPO- PAGO DIFERIDO', 'seleccion' => '0'],
                        ['nombre' => 'TRANSFERENCIA AL EXTERIOR', 'seleccion' => '0'],
                        ['nombre' => 'Transferencia por Servicios', 'seleccion' => '0'],
                        ['nombre' => 'Intereses de FINANCIACIÓN', 'seleccion' => '0'],
                        ['nombre' => 'FINANCIACIÓN DE IMPORTACIÓN', 'seleccion' => '0'],
                        ['nombre' => 'IMPORTACIÓN - CARTA DE CRÉDITO', 'seleccion' => '0'],
                        ['nombre' => 'COD 154 - 155 IMPO- PAGO VISTA', 'seleccion' => '0'],
                        ['nombre' => 'COMPRA DE DÓLARES BILLETES', 'seleccion' => '0'],
                        ['nombre' => 'VENTA DE DÓLARES BILLETES', 'seleccion' => '0'],
                        ['nombre' => 'COD 610 Fletes de importación ganados por buques', 'seleccion' => '0'],
                        ['nombre' => 'VENTA DE EURO BILLETES', 'seleccion' => '0'],
                        ['nombre' => 'CONTRA PARTIDA', 'seleccion' => '0'],
                        ['nombre' => 'COD 627 Pago de Patentes y marcas', 'seleccion' => '0'],
                        ['nombre' => 'OPERACIONES DE MERCADO', 'seleccion' => '0'],
                        ['nombre' => 'COD 104 PreFi de Expo otorgadas por bancos locales', 'seleccion' => '0'],
                        ['nombre' => 'COD 344 Cobros de intereses del exterior', 'seleccion' => '0'],
                        ['nombre' => 'SUSCRIPCION DE SERVICIOS ', 'seleccion' => '0'],
                        ['nombre' => 'CESIÓN DE BONOS FISCALES ', 'seleccion' => '0'],
                        ['nombre' => 'BONOS FISCALES DECRETO 379/01', 'seleccion' => '0'],
                        ['nombre' => 'CESIÓN DE IVA DE EXPORTACIÓN', 'seleccion' => '0'],
                        ['nombre' => 'COBRO DE SERVICIOS ', 'seleccion' => '0'],
                        ['nombre' => 'COD 228 Cobro de Regalías', 'seleccion' => '0'],
                        ['nombre' => 'COD 447 APORTE DE CAPITAL ', 'seleccion' => '0'],
                        ['nombre' => 'CANCELACION DE PRESTAMO EN M/E', 'seleccion' => '0'],
                        ['nombre' => 'IVA DE EXPORTACIÓN', 'seleccion' => '0'],
                        ['nombre' => 'COD 452 PRESTAMOS + DE 1 AÑO DE PLAZO', 'seleccion' => '0'],
                        ['nombre' => 'COD 573 Ingresos de no residentes para el pago de impuestos, tasas y otras contribuciones ', 'seleccion' => '0'],
                        ['nombre' => 'COD 570 Recuperos de impuestos pagados por beneficiarios del exterior', 'seleccion' => '0'],
                        ['nombre' => 'COD 876 Compra de M/E para su entrega a la entidad en pago de financiaciones locales ', 'seleccion' => '0'],
                        ['nombre' => 'COD 231 Servicios empresariales profesionales y técnicos', 'seleccion' => '0'],
                        ['nombre' => 'COD 877 Otras Repatriación de inversiones directas en el país de no residentes', 'seleccion' => '0'],
                        ['nombre' => 'COD 852 PAGO PRESTAMO FINANCIERO DE MAS DE 1 AÑO DE PLAZO', 'seleccion' => '0'],
                        ['nombre' => 'COD 744 PAGO DE INTERESES AL EXTERIOR POR DEUDAS', 'seleccion' => '0'],
                        ['nombre' => 'COD 113 OP Cobros de Expo embarcadas, con permiso de embarque definitivo pendiente', 'seleccion' => '0'],
                        ['nombre' => 'COD 345 Utilidades y dividendos del exterior', 'seleccion' => '0'],
                        ['nombre' => 'COD 223 Servicios de Comunicaciones ', 'seleccion' => '0'],
                        ['nombre' => 'COD 111 Financiación de entidades financieras locales de créditos a cobrar por exportaciones de bien', 'seleccion' => '0'],
                        ['nombre' => 'INTERESES DE PRESTAMO FINANCIERO', 'seleccion' => '0'],
                        ['nombre' => 'COD 476 - Venta de moneda extranjera por otras financiaciones locales otorgadas por la entidad ', 'seleccion' => '0'],
                        ['nombre' => 'COD 106 Cobros de mercaderías no salidas del país y vendidas a terceros países', 'seleccion' => '0'],
                        ['nombre' => 'COD 613 OTROS FLETES', 'seleccion' => '0'],
                        ['nombre' => 'COD 163 Pagos de deudas financieras al exterior originadas en compras de mercancías no  ', 'seleccion' => '0'],
                        ['nombre' => 'COD 116 Cobros Anticipados de Expo aplicados a la Canc de Prefi de Exportaciones', 'seleccion' => '0'],
                        ['nombre' => 'COD 226 GASTOS MEDICOS', 'seleccion' => '0'],
                        ['nombre' => 'COD 610 FLETES DE IMPORTACION GANADOS POR BUQUES', 'seleccion' => '0'],
                        ['nombre' => 'COD 748 RENTA PAGADA A ENTIDADES FINANCIERAS', 'seleccion' => '0'],
                        ['nombre' => 'COD 107 - Devolución de pagos de importaciones de bienes sin registro de ingreso aduanero', 'seleccion' => '0'],
                        ['nombre' => 'B13 Pagos anticipados por la importación de medicamentos críticos Decreto N° 333/20 ', 'seleccion' => '0'],
                        ['nombre' => 'COD 631 Servicios empresariales profesionales y técnicos.', 'seleccion' => '0'],
                        ['nombre' => 'COD 612 Fletes de importación ganados por medios terrestres.', 'seleccion' => '0'],
                        ['nombre' => 'COD 618 Arrendamiento de contenedores, espacios o depósitos en puertos.', 'seleccion' => '0'],
                        ['nombre' => 'COD 632 Comisones bancarias y otros servicios financieros', 'seleccion' => '0'],
                        ['nombre' => 'COD 453 Ventas de participaciones en empresas locales a inversores directos', 'seleccion' => '0'],
                        ['nombre' => 'COD 865 Pagos  por contratos de cobertura de precios de commodities ', 'seleccion' => '0'],
                        ['nombre' => 'CESION DE IVA DE LIBRE DISPONIBILIDAD 2º párrafo ', 'seleccion' => '0'],
                        ['nombre' => 'COD 970 Pagos de Gastos y derechos exigibles a la importación en el país de destino, por ventas DDP', 'seleccion' => '0'],
                        ['nombre' => 'COD 862 INVERSIONES DE PORTAFOLIO EN EL EXT. DE PERSONA JURIDICA', 'seleccion' => '0'],
                        ['nombre' => 'COD 640 Gastos de inscripción y concurrencia a ferias y exposiciones internacionales', 'seleccion' => '0'],
                        ['nombre' => 'COD 152 Pagos anticipados de importaciones de bienes (excepto bienes de capital)', 'seleccion' => '0'],
                        ['nombre' => 'COD 636 Comisiones Comerciales', 'seleccion' => '0'],
                        ['nombre' => 'COD 216 Gastos en el país de buques, aeronaves y medios de transporte terrestre.', 'seleccion' => '0'],
                        ['nombre' => 'B01 Cobro de Exportaciones de Bienes', 'seleccion' => '0'],
                        ['nombre' => 'B02 Cobros Anticipados de Exportaciones de Bienes', 'seleccion' => '0'],
                        ['nombre' => 'B03 Financiaciones del exterior por exportaciones de bienes', 'seleccion' => '0'],
                        ['nombre' => 'B04 Financiación de bancos locales por exportaciones de bienes', 'seleccion' => '0'],
                        ['nombre' => 'B05 Pagos anticipados de importaciones de bienes (excepto bienes de capital)', 'seleccion' => '0'],
                        ['nombre' => 'B06 Pagos diferidos de importaciones de bienes (excepto bienes de capital)', 'seleccion' => '0'],
                        ['nombre' => 'B07 Pagos vista de importaciones de bienes', 'seleccion' => '0'],
                        ['nombre' => 'B08 Pagos por otras compras de bienes al exterior', 'seleccion' => '0'],
                        ['nombre' => 'B09 Compraventa de bienes sin paso por el país y vendidos a terceros países', 'seleccion' => '0'],
                        ['nombre' => 'S01 Mantenimiento y reparaciones', 'seleccion' => '0'],
                        ['nombre' => 'S02 Servicios de fletes', 'seleccion' => '0'],
                        ['nombre' => 'S03 Servicios de transporte de pasajeros', 'seleccion' => '0'],
                        ['nombre' => 'S04 Otros servicios de transportes', 'seleccion' => '0'],
                        ['nombre' => 'S05 Servicios postales y de mensajería', 'seleccion' => '0'],
                        ['nombre' => 'S06 Turismo y Viajes', 'seleccion' => '0'],
                        ['nombre' => 'S07 Servicios de construcción', 'seleccion' => '0'],
                        ['nombre' => 'S08 Primas de seguros', 'seleccion' => '0'],
                        ['nombre' => 'S09 Siniestros', 'seleccion' => '0'],
                        ['nombre' => 'S10 Servicios auxiliares de seguros', 'seleccion' => '0'],
                        ['nombre' => 'S11 Servicios financieros', 'seleccion' => '0'],
                        ['nombre' => 'S12 Servicios de telecomunicaciones', 'seleccion' => '0'],
                        ['nombre' => 'S13 Servicios de informática', 'seleccion' => '0'],
                        ['nombre' => 'S14 Servicios de información', 'seleccion' => '0'],
                        ['nombre' => 'S15 Cargos por el uso de la propiedad intelectual', 'seleccion' => '0'],
                        ['nombre' => 'S16 Servicios de investigación y desarrollo', 'seleccion' => '0'],
                        ['nombre' => 'S17 Servicios jurídicos, contables y gerenciales', 'seleccion' => '0'],
                        ['nombre' => 'S18 Servicios de publicidad, investigación de mercado y encuestas de opinión pública', 'seleccion' => '0'],
                        ['nombre' => 'S19 Servicios arquitectónicos, de ingeniería y otros servicios técnicos', 'seleccion' => '0'],
                        ['nombre' => 'S20 Servicios de arrendamiento operativo', 'seleccion' => '0'],
                        ['nombre' => 'S21 Servicios relacionados con el comercio', 'seleccion' => '0'],
                        ['nombre' => 'S22 Otros servicios empresariales', 'seleccion' => '0'],
                        ['nombre' => 'S23 Servicios audiovisuales y conexos', 'seleccion' => '0'],
                        ['nombre' => 'S24 Otros servicios personales, culturales y recreativos', 'seleccion' => '0'],
                        ['nombre' => 'S25 Servicios del gobierno', 'seleccion' => '0'],
                        ['nombre' => 'S26(anulado)Gtos y derechos exigibles a la importación por operaciones realizadas bajo condición DDP', 'seleccion' => '0'],
                        ['nombre' => 'I01 Intereses del exterior', 'seleccion' => '0'],
                        ['nombre' => 'I02 Intereses locales', 'seleccion' => '0'],
                        ['nombre' => 'I03 Utilidades y dividendos', 'seleccion' => '0'],
                        ['nombre' => 'I04 Remuneración de empleados', 'seleccion' => '0'],
                        ['nombre' => 'I05 Alquiler de inmuebles', 'seleccion' => '0'],
                        ['nombre' => 'I06 Otras rentas', 'seleccion' => '0'],
                        ['nombre' => 'I07 Transferencias personales', 'seleccion' => '0'],
                        ['nombre' => 'I08 Otras transferencias corrientes', 'seleccion' => '0'],
                        ['nombre' => 'C01 Adquisiciones/disposiciones de activos no financieros no producidos', 'seleccion' => '0'],
                        ['nombre' => 'C02 Transferencias de capital', 'seleccion' => '0'],
                        ['nombre' => 'A01 Instrumentos de deuda entre empresas afiliadas', 'seleccion' => '0'],
                        ['nombre' => 'A02 Inversiones de residentes en inmuebles en el exterior', 'seleccion' => '0'],
                        ['nombre' => 'A03 Otras inversiones directas de residentes', 'seleccion' => '0'],
                        ['nombre' => 'A04 Títulos de deuda', 'seleccion' => '0'],
                        ['nombre' => 'A05 Derivados financieros', 'seleccion' => '0'],
                        ['nombre' => 'A06 Préstamos otorgados a no residentes', 'seleccion' => '0'],
                        ['nombre' => 'A07 Depósitos de residentes en el exterior', 'seleccion' => '0'],
                        ['nombre' => 'A08 Otras inversiones en el exterior de residentes', 'seleccion' => '0'],
                        ['nombre' => 'A09 Billetes y cheques de viajeros en poder de residentes', 'seleccion' => '0'],
                        ['nombre' => 'A10 Débito/crédito de moneda extranjera en cuentas locales por transferencias con el exterior', 'seleccion' => '0'],
                        ['nombre' => 'A11 Suscripción primaria de entidades financieras de títulos valores', 'seleccion' => '0'],
                        ['nombre' => 'A12 Otras operaciones de compra/venta de entidades financieras de títulos valores', 'seleccion' => '0'],
                        ['nombre' => 'A13 (ANULADO) Ingreso de divisas del exterior acreditadas en cuentas locales', 'seleccion' => '0'],
                        ['nombre' => 'A14 Operaciones de empresas procesadoras de pagos ', 'seleccion' => '0'],
                        ['nombre' => 'A15 Ingresos de divisas vinculadas a exportaciones de bienes pendientes de liquidación', 'seleccion' => '0'],
                        ['nombre' => 'P01 Instrumentos de deuda entre empresas afiliadas', 'seleccion' => '0'],
                        ['nombre' => 'P02 Inversiones de no residentes en inmuebles en el país', 'seleccion' => '0'],
                        ['nombre' => 'P03 Otras inversiones directas de no residentes', 'seleccion' => '0'],
                        ['nombre' => 'P04 Títulos de deuda', 'seleccion' => '0'],
                        ['nombre' => 'P05 Derivados financieros', 'seleccion' => '0'],
                        ['nombre' => 'P06 Préstamos financieros de organismos internacionales y agencias oficiales de crédito', 'seleccion' => '0'],
                        ['nombre' => 'P07 Préstamos financieros habilitados para aplicar divisas de exportaciones', 'seleccion' => '0'],
                        ['nombre' => 'P08 Otros préstamos financieros', 'seleccion' => '0'],
                        ['nombre' => 'P09 Líneas de crédito del exterior', 'seleccion' => '0'],
                        ['nombre' => 'P10 Depósitos locales de no residentes', 'seleccion' => '0'],
                        ['nombre' => 'P11 Otras inversiones de no residentes', 'seleccion' => '0'],
                        ['nombre' => 'P12 Otras financiaciones locales otorgadas por la entidad (excluida la financiación de', 'seleccion' => '0'],
                        ['nombre' => 'A17 Transferencias desde/al exterior asociadas a operaciones entre residentes ', 'seleccion' => '0'],
                        ['nombre' => 'DEVOLUCION DE PAGOS DE IMPORTACION', 'seleccion' => '0'],
                        ['nombre' => 'TRANFERENCIAS DOLARES MEP', 'seleccion' => '0'],
                        ['nombre' => 'B10 Pagos de deudas comerciales por importaciones de bienes sin registro de ingreso aduanero ', 'seleccion' => '0'],
                        ['nombre' => 'B12 Pagos anticipados de importaciones de bienes de capital', 'seleccion' => '0'],
                        ['nombre' => 'A19 Constitucion de depositos en moneda extranjera para aplicar al pago de servicios de deuda', 'seleccion' => '0'],
                        ['nombre' => 'Gestion de Recupero de IVA ', 'seleccion' => '0'],
                        ['nombre' => 'B15 Pagos de deudas comerciales por la importacion de bienes con agencias oficales de credito ', 'seleccion' => '0'],
                        ['nombre' => 'B16 Pagos con r i a p por importacion de medicamentos y bienes para atencion medica de la poblacion', 'seleccion' => '0'],
                        ['nombre' => 'B17 Pagos deudas comerciales importacion medicamentos criticos de persona juricadas ', 'seleccion' => '0'],
                        ['nombre' => 'B18 Pagos vista de importaciones de insumos para produccion local de bienes', 'seleccion' => '0'],
                        ['nombre' => 'B19 Pagos deudas comerciales importaciones insumos prod loc bienes sin r i a ', 'seleccion' => '0'],
                        ['nombre' => 'B20 Pagos vista de importaciones de bienes de capital', 'seleccion' => '0'],
                        ['nombre' => 'B21 Pago deudas comerciales impo bienes de capital sin r i a', 'seleccion' => '0'],
                        ['nombre' => 'A15 Ingreso de divisas vinculadas a exportaciones de bienes pendientes de liquidación', 'seleccion' => '0'],
                        ['nombre' => 'B22 Pagos diferidos de importaciones de bienes de capital', 'seleccion' => '0'],
                        ['nombre' => 'S31 Servicios de fletes por operaciones de exportaciones de bienes', 'seleccion' => '0'],
                        ['nombre' => 'S27 Otros servicios de salud', 'seleccion' => '0'],
                        ['nombre' => 'S28 Enseñanzas Educativas', 'seleccion' => '0'],
                        ['nombre' => 'S29 Operaciones por retiro o consumo con tarjcred resid con prov no resid o de no resid con prov arg', 'seleccion' => '0'],
                        ['nombre' => 'S30 Servicios de fletes por operaciones de importaciones de bienes', 'seleccion' => '0'],
                        ['nombre' => 'S32 Ingresos por cobros de exportaciones de servicios no liquidados (Decreto 549/23)', 'seleccion' => '0'],
                        ['nombre' => 'S33 Registgro de importaciones de servicios por adjudicación de bonos BOPREAL', 'seleccion' => '0'],
                        ['nombre' => 'P14 Depósitos locales de no residentes asociados a ingresos destinados a viajes', 'seleccion' => '0'],
                        ['nombre' => 'P15 Compra de residentes para su entrega a la entidad en pago saldo mon ext por uso tarj credito', 'seleccion' => '0'],
                        ['nombre' => 'P16 Pagos de principal de deudas financieras con el exterior originadas en importaciones de servicio', 'seleccion' => '0'],
                        ['nombre' => 'P17 Registro de refinanciación de deuda comercial en el marco del pto 20 Com A 7626', 'seleccion' => '0'],
                        ['nombre' => 'P18 Registro de endeudamineto financiero habilitado para aplicar div de expo Com A 7770 y compl', 'seleccion' => '0'],
                        ['nombre' => 'P19 Registro de endeudamiento financiero con el exterior asociados a la impo de BK -Decreto 234/21-', 'seleccion' => '0'],
                        ['nombre' => 'P20 Registro de aporte de inversión directa en especie por BK (marco Decreto 234/21)', 'seleccion' => '0'],
                        ['nombre' => 'A20 Billetes en moneda extranjera por instruccion judicial', 'seleccion' => '0'],
                        ['nombre' => 'A21 Billetes en moneda extranjera de repr dipl/ cons/ org int/ pers diplom', 'seleccion' => '0'],
                        ['nombre' => 'A22 Acreditación de cobros de exportaciones de bienes y servicios', 'seleccion' => '0'],
                        ['nombre' => 'A23 Constitución de depósitos en el exterior para afectar al pago de impo. de combustibles o energia', 'seleccion' => '0'],
                        ['nombre' => 'B23 Reg de financ.de impo bienes elegible para aplicar cobros en div por expo bs. Com A7770 y compl.', 'seleccion' => '0'],
                        ['nombre' => 'B24 Reg. de financiac. de impo de BK computable en el marco del Decreto 234/21', 'seleccion' => '0'],
                        ['nombre' => 'B25 Ingresos por cobros de expo bienes no liqjuidados . Decreto 443/23 y compl -', 'seleccion' => '0'],
                        ['nombre' => 'B26 Registro de importaciones de bienes por adjudicación bonos BOPREAL ', 'seleccion' => '0'],
                ];

            foreach($referencias as $referencia){
                Referencia::create([
                                    'nombre' => $referencia['nombre'],
                                    'seleccion' => $referencia['seleccion']
                ]);
        }
    }
}
